### ISSUE TITLE
document options to keep the README up-to-date

### ISSUE THREAD

**Issue by maelle** [ropensci/allcontributors#15]
E.g. link to GitHub Action workflows that knit the README on schedule (as we have in ropensci/software-review) https://github.com/ropensci/software-review/blob/master/.github/workflows/main.yml

**Comment by mpadge** [comment]
Yeah, great idea. It shall be done. Thank you!

**Comment by maelle** [comment]
@mpadge friendly reminder

**Comment by mpadge** [comment]
Oh yeah, thank you!!

**Comment by mpadge** [comment]
First workflow run ran perfectly: https://github.com/ropensci/allcontributors/actions/runs/11894746363/job/33142671637.
I'll link to [file in this repo](https://github.com/ropensci/allcontributors/blob/main/.github/workflows/allcontributors.yml) as an example

**Comment by maelle** [comment]
another idea that could be mentioned, without CI: if you use usethis' release issue checklist, you can store custom items as an internal function. One item could be "run allcontributors". See https://usethis.r-lib.org/reference/use_release_issue.html#customization

**Comment by maelle** [comment]
- you create the function in any package where you want the item to appear in checklists.
- for releases you use `usethis::use_release_issue()` that opens an issue in the repository. An item would remind to update the allcontributors list.

**Comment by maelle** [comment]
example https://github.com/EMODnet/emodnet.wfs/blob/60ba8dc578911d3169d15f032521651ac51a898c/R/emodnet.wfs-package.R#L45
